load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "zlib-repo",
    build_file = "@//:third_party/BUILD.zlib",
    strip_prefix = "zlib-1.2.6",
    url = "https://github.com/madler/zlib/archive/v1.2.6.tar.gz",
)
